import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/Providers";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
	return (
		<html className="bg-black" lang="en">
			<body className={`bg-black text-white antialiased`}>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
}
